### PR TITLE
fix: Display year if snooze time is not in current year

### LINKED ISSUE #211: When snoozing a tab in a different year, notification bar only shows date and hour
If I snooze a tab a year from now, e.g. Feb 24 2018 @ 5 PM, notification only shows Feb 24 at 5 PM, which is potentially confusing.

On the other hand, the Manage snoozed tabs panel correctly shows the year when a tab is expected to wake up in a different year.

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #211.

### CODE REVIEW

File: src/lib/times.js [hunk 1]
```diff
@@ -77,7 +78,8 @@ export function confirmationTime(time, timeType) {
   if (upcoming.minutes()) {
     timeStr = getLocalizedDateTime(upcoming, 'confirmation_time');
   }
-  const dateStr = getLocalizedDateTime(upcoming, 'confirmation_date');
+  const dateStr = getLocalizedDateTime(upcoming,
+    (upcoming.year() === thisYear) ? 'confirmation_date' : 'confirmation_date_with_year');
```
Comment (bwinton) [inline src/lib/times.js]: Could we switch this to the `let`/`if()` like timeStr?  I'm kinda allergic to the ternary `?:` operator…  (I mean, not totally allergic, but it often seems a little too clever for its own good.  :wink:)

Comment (bwinton) [inline src/lib/times.js]: Oh, my other thought was that we could only show the date if the year wasn't this year, and the month and day was after today.  (i.e. on Dec 31st, a date of Jan 17th isn't going to be assumed to be in this year.)  But that's not really needed in this patch, and I'm not entirely sure it's a good idea.  🙂

**Comment by ericawright** [comment]
(tested, and it works as described btw)

File: src/lib/times.js (hunk 1 above)
Comment (lmorchard) [inline src/lib/times.js]: Well, I was trying to avoid re-running `getLocalizedDateTime` since all that changed was the name of the string. But, I can use an if statement instead

**Comment by lmorchard** [comment]
Rebased against master, updated to use if statement instead of ternary, will merge after circleci passes
