### PR TITLE
fix: Don't wake tabs up in incognito windows.

### LINKED ISSUE #287: Opens on Private Browsing
To avoid awaking my work tabs via the "Restore Session" button when you restart firefox, I right clicked it and selected private browsing. Snooze Tabs reopened one of the pages I had set for today. Perhaps an open for "enable on Private Browsing" would be appropriate, as this feature may also be an advantage, as I may be able to open one tab without restarting my entire session. However, some tabs, especially work related, I do not want to reopen upon opening a separate window

edit: I also cannot seem to put the tab back on snooze for next Tuesday. Being able to 'transfer' tabs from this private browsing (due to the nature in which I use Firefox) would be highly valuable. Sorry, I'm notorious for using programs in unintended and sometimes complicated ways.

This is an excellent management system, though. Very useful for my "schedule."

### PR DESCRIPTION
**Pull request by bwinton**
`Next Open` now opens on the active non-private-browsing window in the next session (or the first non-private-browsing window if the active window is private, or the window it was snoozed from if that window isn't private)…

It's a little complicated to describe, but I think it's doing the right thing in all the cases I could think of…

Fixes #287.

### CODE REVIEW

File: src/background.js [hunk 1]
```diff
@@ -93,21 +94,40 @@ function init() {
...
+    if (items.length) {
+      browser.windows.onCreated.addListener(handleNextOpen);
+    }
   }).catch(reason => {
     log('init storage get rejected', reason);
   });
 }
 
+function handleNextOpen(window) {
+  if (!window.incognito) {
```
Comment (lmorchard) [inline src/background.js]: Could just do `if (window.incognito) { return; }` here and drop a level of indent throughout the rest.

File: src/background.js [hunk 2]
```diff
@@ -93,21 +94,40 @@ function init() {
...
+    getNextOpenAlarms().then(items => {
+      if (items.length) {
```
Comment (lmorchard) [inline src/background.js]: Same here, an `if (!items.length) { return; }` could de-dent this block

File: src/background.js [hunk 3]
```diff
@@ -93,21 +94,40 @@ function init() {
 
   getMetricsUUID().then(clientUUID => {
     Metrics.init(clientUUID);
-    return getAlarms();
+    return getNextOpenAlarms();
```
Comment (lmorchard) [inline src/background.js]: Hmm, `getNextOpenAlarms` gets called twice - maybe don't need this first call, since `handleNextOpen` does it again & checks length anyway? Or maybe I'm missing something in the logic here?

File: src/lib/storage.js [hunk 4]
```diff
@@ -24,6 +25,12 @@ export function getAlarms() {
   return getAlarmsAndProperties().then(data => data.alarms);
 }
 
+export function getNextOpenAlarms() {
+  return getAlarms().then(items => {
+    return Object.entries(items).filter(item => item[1].time === NEXT_OPEN);
```
Comment (lmorchard) [inline src/lib/storage.js]: Could use `Object.values` and change `item[1]` to just `item`

File: src/background.js (hunk 3 above)
Comment (bwinton) [inline src/background.js]: So, I did it that way so that we wouldn't register the window listener if we didn't need to, but it's probably not that expensive, so I'll remove it.

File: src/background.js (hunk 1 above)
Comment (bwinton) [inline src/background.js]: Done.

File: src/background.js (hunk 2 above)
Comment (bwinton) [inline src/background.js]: Done.

File: src/lib/storage.js (hunk 4 above)
Comment (bwinton) [inline src/lib/storage.js]: And done.  🙂
