### PR TITLE
fix: Display snoozed tab's site favicon.

### LINKED ISSUE #74: Display snoozed tab's site favicon instead of generic icon?
Probably full of scarier edge cases (low resolution favicons, cross-site-loading, etc), but not sure if the snoozed tab UI should attempt to use the site's favicon instead of the generic [src/icons/nightly.svg](https://github.com/bwinton/SnoozeTabs/blob/b2ea0b116224006ebb5cf82ad1f30c809c5c4683/src/icons/nightly.svg) icon for all results.

menubar_and_congress_begins_to_search_for_funds_to_help_trump_build_border_wall_-_la_times_and_react_storybook

### PR DESCRIPTION
**Pull request by bwinton**
Fixes #74.

### CODE REVIEW

File: src/popup/snooze-content.js [hunk 1]
```diff
@@ -47,7 +47,8 @@ function scheduleSnoozedTab(time) {
           'time': time.valueOf(),
           'title': tab.title || 'Tab woke up…',
           'url': tab.url,
-          'windowId': tab.windowId
+          'windowId': tab.windowId,
+          'icon': tab.favIconUrl
```
Comment (lmorchard) [inline src/popup/snooze-content.js]: Huh. Somehow, I thought this would be harder.
