### PR TITLE
fix: Add a unique string to the bookmark folder.

### LINKED ISSUE #273: Bookmark management doesn't play well with Sync
While going through my personal sync logs, I noticed some strangeness which I think I've narrowed down to https://github.com/bwinton/SnoozeTabs/blob/de20a9293e52eda6619c241a4256556c0d7975b0/src/background.js#L161. I see 2 main issues here:

* For a user with a Sync account and only 1 of the devices having this addon enabled, the fact that the menu is deleted and then repopulated every time is causing sync churn - sync notices the deletion of the "old" item and syncs the deletion. It then notices the creation of another identical bookmark (differing only by GUID) and syncs that. Other devices then do a little dance processing the deletion and the de-dupe logic does strange things.

* Worse, consider a Sync account where all devices have this addon enabled. Sync will keep this folder synced between multiple devices. This means that both devices will "battle" for ownership of that folder, with Sync doing its best to ensure all devices have the same copies. At any time, it seems that all devices will have the snoozed tabs from one arbitrary device, and which device that is appearing to change randomly.

cc @kitcambridge

### PR DESCRIPTION
**Pull request by bwinton**
To prevent sync fights.

Fixes #273.
Again, sorta.

### CODE REVIEW

**Comment by bwinton** [comment]
Also tagging @rnewman and @flodolo for their thoughts…

File: locales/en-US/snoozetabs.properties [hunk 1]
```diff
@@ -3,7 +3,8 @@
 extDesc=An add-on to let you snooze your tabs for a while.
 popupTitle=Snooze tab until…
 contextMenuTitle=Snooze tab until…
-bookmarkFolderTitle=Snoozed Tabs
+# "{unique_id}" is a per-device id to stop Sync from complaining.
```
Comment (flodolo) [inline locales/en-US/snoozetabs.properties]: Localizers are not interested in why you're adding an ID, more if they should localize it or not.

Maybe something like "{unique_id} is an identifier added to the bookmark folder's name to avoid conflicts. Do not translate it"

**Comment by rnewman** [comment]
I think this is fine for the experiment. The ideal is that you get uniqueness in the ID and descriptiveness in the name, but Sync will smush two folders with the same name and parent, so here we are!

File: locales/en-US/snoozetabs.properties (hunk 1 above)
Comment (bwinton) [inline locales/en-US/snoozetabs.properties]: :+1:

File: src/background.js [hunk 2]
```diff
@@ -42,16 +42,18 @@ function init() {
   log('init()');
   browser.runtime.onInstalled.addListener((details) => {
     if (details.reason === 'install') {
-        const title = browser.i18n.getMessage('bookmarkFolderTitle');
-        browser.bookmarks.search({title: title}).then(folders => {
+      getMetricsUUID().then(clientUUID => {
```
Comment (lmorchard) [inline src/background.js]: I'd say let's not use the metrics UUID for this because it's potentially close to PII, but all I have is vague handwaving and no real scenarios of doom.
