### PR TITLE
Include language direction on confirmation bar injected into pages

### LINKED ISSUE #281: On HE build, the panels and confirmation notification are not mirrored in the RTL mode
[Affected versions]:
- Firefox 55.0a1
- Snooze Tabs 1.0.15

[Affected Platforms]:
- All Windows
- All MAC OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 22/03/2017) loaded as a temporary add-on.
- Have the Hebrew [he] Firefox locale build installed.

[Steps to reproduce]:
1. Open the localized Firefox build with the profile from prerequisites.
2. Navigate to any website.
3. Click the Snooze Tabs button and observe how the translated items are displayed in the panel.

[Expected result]:
- All items are displayed from right to left (flipped) and correctly translated in Hebrew.

[Actual result]:
- All items are correctly translated in Hebrew, but are wrongly displayed from left to right (normal)

[Notes]:
- This issue also affects the confirmation notification. 
- Please see the Screenshot attached:

rtl

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #281.

### CODE REVIEW

File: src/lib/confirm-bar.js [hunk 1]
```diff
@@ -37,7 +40,7 @@ chrome.runtime.onMessage.addListener(function({message, iconData, closeData}) {
     confirmationBar = document.createElement('div');
     document.body.appendChild(confirmationBar);
   }
-  confirmationBar.outerHTML = `<div id="${confirmationId}">
+  confirmationBar.outerHTML = `<div id="${confirmationId}" dir="${langDir}">
```
Comment (bwinton) [inline src/lib/confirm-bar.js]: I'm a little surprised we don't need to do any CSS stuff here, but there you go, I guess.  ¯\_(ツ)_/¯

Comment (lmorchard) [inline src/lib/confirm-bar.js]: Yeah, I was kind of shocked and just kind of whistled and walked away
