### PR TITLE
fix: Disable the snooze button for special urls.

### LINKED ISSUE #59: Attempting to snooze special urls causes chaos…
`about:debugging` for instance, can't be restored (nor can `about:newtab` or some others).
So, we snooze it, and it goes away, but we can't open it from the Manage menu, and when its alarm fires, it fails to restore (and is thus lost forever), and the error prevents us from rescheduling the next alarm, so the whole thing breaks!  😢

Maybe we should check our ability to restore a tab before we snooze it?  Or just whitelist http/https urls and only deal with those?

### PR DESCRIPTION
**Pull request by bwinton**
We can only restore certain urls so let's not let people snooze them!
But we don't want to disable the button entirely, so if they click it, just show them the manage panel.

Fixes #59.

### CODE REVIEW

File: src/icons/Bell Icon.svg [hunk 1]
```diff
@@ -1,28 +1,28 @@
...
-		l0.2,0.3L9,5.6c-0.3,0.2-0.7,0.3-1,0.5C6.7,7,5.8,8.3,5.3,9.8c-0.2,0.7-0.4,1.4-0.4,2.2v1.4c0,2-0.8,3.9-2.2,5.3
-		c-0.3,0.3-0.3,0.7-0.2,1c0.1,0.3,0.4,0.6,0.8,0.6h4.9h0.3v0.3c0,1.9,1.5,3.4,3.4,3.4s3.4-1.5,3.4-3.4v-0.3h0.3h4.9
-		c0.4,0,0.7-0.3,0.8-0.6C21.6,19.5,21.6,19.1,21.3,18.7z M12,1.8c0.9,0,1.6,0.7,1.6,1.6S12.9,4.9,12,4.9s-1.6-0.7-1.6-1.6
-		C10.5,2.5,11.1,1.8,12,1.8z M13.1,21.7c-0.3,0.3-0.7,0.5-1.1,0.5c-0.9,0-1.6-0.7-1.6-1.6v-0.3h0.3h2.5h0.3l0,0.3
-		C13.6,21,13.4,21.4,13.1,21.7z M14.8,11c0,0.3-0.1,0.6-0.4,0.9l-2.9,3.2h2.6c0.4,0,0.7,0.3,0.7,0.7s-0.3,0.7-0.7,0.7h-4
-		c-0.5,0-0.9-0.3-0.9-0.7v0c0-0.3,0.1-0.6,0.4-0.9l2.9-3.2H10c-0.4,0-0.7-0.3-0.7-0.7c0-0.4,0.3-0.7,0.7-0.7h3.9
-		C14.4,10.3,14.8,10.6,14.8,11L14.8,11z"/>
-</g>
-</svg>
+<?xml version="1.0" encoding="utf-8"?>
```
Comment (lmorchard) [inline src/icons/Bell Icon.svg]: Hmm, so in Dev Edition, the disabled icon is lighter and the enabled icon is darker. That made me think the states were switched. But, this sounds like a variation on Issue #67. 

Maybe we want to think about changing the icon shape itself rather than the color? (i.e. circle-with-crossbar over the bell? just a random thought)

File: src/background.js [hunk 2]
```diff
@@ -18,11 +18,36 @@ function log(...args) {
...
 function init() {
   log('init()');
   browser.alarms.onAlarm.addListener(handleWake);
   browser.notifications.onClicked.addListener(handleNotificationClick);
   browser.runtime.onMessage.addListener(handleMessage);
+  browser.tabs.onUpdated.addListener(updateButtonForTab);
+  browser.tabs.onCreated.addListener(tab => {
+    updateButtonForTab(tab.id, {url: tab.url});
+  });
+  browser.tabs.query({}).then(tabs => {
```
Comment (lmorchard) [inline src/background.js]: Not 100% sure what this bit does. Seems like it runs through all tabs and flips the button to enabled / disabled for each in turn. Does it just end up on the current tab in the end?

Comment (lmorchard) [inline src/background.js]: Maybe we want this here instead?
```
browser.tabs.query({currentWindow: true, active: true})
```

Comment (bwinton) [inline src/background.js]: It does, and we want it the way it is because we need to set the states for the existing tabs, and we don't get a `tabs.onUpdated` even when we switch tabs.

(i.e. If we start with two tabs, "about:home" and "about:addons", load the extension, we want it to be disabled on both.)

File: src/icons/Bell Icon.svg (hunk 1 above)
Comment (bwinton) [inline src/icons/Bell Icon.svg]: Yeah, I'm not sure we can fix #67.  At least, not yet.
