### PR TITLE
fix: Only build manually selected locales for production

### LINKED ISSUE #275: Several areas are not localized in Asturian [ast]
[Affected versions]:
- Nightly 55.0a1
- Snooze Tabs 1.0.15 (built on 03/20/2017)

[Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Snooze Tabs add-on version (1.0.15 -dev, built on 03/20/2017) loaded as a temporary add-on.
- Have the Asturian [ast] Firefox locale build installed.

The following areas are displayed in English and should be displayed in Asturian [ast]:
- All the strings in the "Manage SnoozedTabs" panel.
- The "Real Soon Now!", "Next Open" and "Pick a Date/Time" snoozing options.
- "This tab will snooze until" string in the notification bar.
- The "Snooze!" button in the "Pick a Date/Time" panel.
- The "SnoozeTabs" context-menu "Real Soon", "Next Open" options..
- The "SnoozeTabs" tooltip from the "SnoozeTabs" button in the browser toolbar. 

[Notes]:
- Attached a screen shot of the affected areas:
issue_collage

### PR DESCRIPTION
**Pull request by lmorchard**
- New `config.productionLocales` property in `package.json` to
  select locales for production build

- `bin/build-locales.js` helper script to select locales for
  `pontoon-to-webext`

- `cross-spawn` dependency to try to make this work on Windows

Fixes #275.

### CODE REVIEW

File: bin/build-locales.js [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+}
+
+spawn.sync('pontoon-to-webext', [], {
+  stdio: 'inherit',
+  env: Object.assign(
+    {},
+    process.env,
+    { SUPPORTED_LOCALES: locales }
+  )
+});
```
Comment (bwinton) [inline bin/build-locales.js]: Should we get pontoon-to-webext to just check a key in the npm config (if it exists), so that we could remove this extra file?
…
I guess we would still want to do it only if it was for production, and that doesn't seem like something that pontoon-to-webext would really be interested in, so having this file seems fine.

Comment (lmorchard) [inline bin/build-locales.js]: Yeah, I figured this was more a Snooze Tabs specific hack for npm scripts switching on NODE_ENV==production and using the package.json config. Other projects might want to do this differently (e.g. if they're using gulp or webpack)

**Comment by lmorchard** [comment]
> Assuming spawn.sync will propagate errors from pontoon-to-webext so that the build will stop if we mess something up, I'm good with this change.

Good catch, because it did not! Just tweaked that and updated. Will merge on tests passing

**Comment by bwinton** [comment]
>Will merge on tests passing

:+1:  🙂
